site_name: How Django Works
dev_addr: 0.0.0.0:8000

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - Views: views.md
  - Request: request.md
  - Refenreces: references.md
